# More on Lists, Arrays, and Functions

## Exercise 1:  Lists review

Write a function merge() that merges two lists into one list that contains every item exactly once, in sorted order.  So merge([2,1,3],[3,3,4]) should produce [1,2,3,4].

Recall for this:
* a in b checks whether item a is in list b
* c.sort() sorts list c

In [ ]:
def merge(list1, list2):
    combined_raw = list1 + list2
    combined = []
    for item in combined_raw:
        if not item in combined:
            combined.append(item)
    combined.sort()
    return combined

merge([2,1,3], [3,3,4])

# More array functionality

* Arrays have "attributes" that let you know useful things like the number of dimensions (.ndim), the dimensions themselves (.shape, which is a tuple), and the total number of items (.size).

In [1]:
import numpy as np

myarray = np.array([[3, 1, 2], [2, 0, 8]])

print(myarray.ndim)
print(myarray.shape)
print(myarray.size)

2
(2, 3)
6


For shape, the convention is (rows, columns), and it matches the convention for how the array is indexed.  It's common to "unpack" this immediately into variables, so that they can be used for iteration.

In [ ]:
rows, columns = myarray.shape
for i in range(rows):
  for j in range(columns):
    myarray[i,j] += 2
print(myarray)


* Two common methods to see in code are reshape() and flatten().  Reshape creates a new array with the same data but a different shape.  (Note that it may or may not create a new copy of the data; it may just create a reference to the same buffer of values.)  Flatten() returns a copy of the array that is 1D.

In [3]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)
Ashaped = A.reshape(2,3)
print(Ashaped)
print(A.flatten())

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Exercise 2

 Write a function that returns True iff its arguments A and B are matrices that can be legally multiplied (AB).  That is, the number of columns of A must equal the number of rows of B.  You can assume A and B are both 2D arrays.

In [ ]:
def legal_mult(A,B):
    return A.shape[1] == B.shape[0]

A = np.array([[1,2,3,4],[5,6,7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(legal_mult(A,B)) # should return True
print(legal_mult(B,A)) # should return False

# A functional style:  map and lambda

Python is mostly what's called an imperative language - commands are executed one after the other in sequence.   C++ and Java are two other imperative languages.

Another style, functional programming, treats the program more like a giant nested function that needs evaluation.  Scheme and Lisp are in this category of language.  Things aren't written one command after the other, but rather everything is nested.  Some programming languages people like these languages because of their elegance.



But Python does support some functionality that came from the functional programming side, and languages that interact with big, distributed data often find it useful to have the following concepts around, too.

First, there's "map."  This takes a function and applies it to every element of a list.

In [4]:
def appendish(x):
  return x + "ish"

list(map(appendish, ["cool","interesting","neat"]))

['coolish', 'interestingish', 'neatish']

Notice that we passed a function as an argument.

Also notice that we had to pass the result to list() to get a final result; this is because map does what's called "lazy evaluation" and doesn't calculate anything until it needs to.  list() forces it to generate the list.


Map's little helper is "lambda."  This creates what's called an *anonymous function*.  If the function's only going to be used for the map, the code might be more readable if you just define the function right where you use it.

In [ ]:
list(map(lambda x: x + "ish", ["cool","interesting","neat"]))

Lambda quickly defines its function, giving arguments (x) and what should be returned (x + "ish").  It's slick when you see an opportunity for it.

Related to map and lambda is "filter."  While map creates a list of elements that is as long as the original, "filter" only keeps elements that pass the test of a Boolean function returning True.  That function could be an anonymous function created by lambda.

In [7]:
# Named function version
def isPositive(x):
  return x > 0

my_list = [5, 0, -1, 2]

new_list = list(filter(isPositive, my_list))
print(new_list)

[5, 2]


In [8]:
# Anonymous version
list(filter(lambda x:  x > 0, [5, 0, -1, 2]))

[5, 2]

Often a lambda is used to just specialize a more general function.

In [9]:
def longerThan(mystr, thresh):
  return len(mystr) > thresh

strlist = ["foo", "bar", "baz", "f"]
list(filter(lambda x: longerThan(x,2), strlist)) # specializing an existing function

['foo', 'bar', 'baz']

# Exercise 3

Try to write an expression that takes a list of strings and, using map, "doubles" each string ("foo" becomes "foofoo" etc).

# Exercise 4

Try to write an expression that takes a list of numbers and, using filter, filters out all the 2's.


In [10]:
list(map(lambda x: x + x, ["a", "b", "c"]))

['aa', 'bb', 'cc']

In [14]:
list(filter(lambda x: x != 2, [2, 1, 5, 7, 2]))

[1, 5, 7]