In [ ]:
mylist = ['A', 'B', '1']

def contains_number(mylist):
  for item in mylist:
    if item.isdigit():
      return True # number found
  return False

print(contains_number(mylist))

True


In [ ]:
list(map(lambda s: s.lower(), mylist))

['a', 'b', '1']

In [ ]:
[s.lower() for s in mylist]

['a', 'b', '1']

In [1]:
import numpy as np
table = np.zeros((11,11))
for i in range(11):
  for j in range(11):
    table[i][j] = i*j
print(table)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  0.   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  0.   6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  0.   7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  0.   8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


In [4]:
def unique(lst):
  itemset = set()
  for item in lst:
    if item in itemset:
      return False
    itemset.add(item)
  return True

print(unique(animals))
print(unique(['bear','lion']))

False
True


In [3]:
animals = "panda,lion,panda,lion,bear"

def animalhasher(animals):
  animalist = animals.split(",")
  animaldict = {}
  for animal in animalist:
    if animal in animaldict:
      animaldict[animal] += 1
      animaldict[animal + "s"] = animaldict[animal]
    else:
      animaldict[animal] = 1
  return animaldict

animalhasher(animals)

{'panda': 2, 'lion': 2, 'pandas': 2, 'lions': 2, 'bear': 1}